# Generated by Django 6.0.2 on 2026-02-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_num', models.CharField(max_length=100, unique=True)),
                ('candidate_name', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=100)),
                ('certificate_url', models.URLField()),
                ('issued_date', models.DateField()),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
    ]
